# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: JD Engelbrecht
title: Full-Stack Developer
email: jdengelbrecht1@outlook.com
website: https://github.com/afrotter

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: 
github_username:  afrotter
# stackoverflow_username: "00000001"
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: jameswgrant
linkedin_username: jd-engelbrecht-b96267232
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Greetings! My name is JD, and I find joy in bringing digital creations to life. 
 
 My passion for web development was ignited in 2016 with building and maintaining WordPress websites for various companies. With a professional background in IT and network administration, I have gained valuable experience from a medium-sized internet service provider. 
 
 Currently, I am pursuing a part-time degree in Business Management while continuously refining my developer skills. I am delighted to present my portfolio, which showcases my expertise and enthusiasm for creating impactful web-based solutions.

 Here are a few technologies that I've worked with recently:
 <mark>Node.js</mark> <mark>React</mark> <mark>JavaScript (ES6+)</mark> <mark>WordPress</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: QR Code Generator
       # link: github.com/afrotter/qr_code_generator
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/afrotter/qr_code_generator
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Built in <mark>JavaScript</mark>, this app allows you to generate an adjustable size QR code for any valid URL in seconds.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vinet Internet Solutions
        link: vinet.co.za
        # link_text: boringcompany.com
        sub_title: Technical Support and Network Administration
        caption: 2016 - 2020
        description: | # this will include new lines to allow paragraphs
            Oversaw technical support team responsible for +/- 2000 clients
            Design and deployment of ISP network infrastructure
            Company website development, including client companies

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Akademia
        caption: 2021 - Present
        sub_title: BCom Business Management
        description: | # this will include new lines to allow paragraphs
          In progress of my third year at Akademia. Focussing on project management, supply chains and international business at the moment.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software development some of my other interests and hobbies are:
      - Hiking
      - Game design
      - Chess


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

"terminal.integrated.setLocaleVariables": true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
